### ISSUE TITLE
[new feature request]restart owfs server when no sensors found

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.owfs#10]
From time to time need to restart the raspi where OWFS is installed. Sometimes the OWFS server hangs and I need to manually restart it. 
Would it be possible to remote send "sudo service owserver restart" when  no sensor is detected (Cannot read value of /28.F6FFBBE01083/temperature: Error: Error: connect ECONNREFUSED 192.168.178.xx:4304)

**Comment by Apollon77** [comment]
For such commands normally "root" is needed, so no an adapter should not do that in my eyes

**Comment by thost96** [comment]
@Apollon77  maybe it would be nice to have a state for that, so you could restart the service using js oder node-red (like a trigger)?
