### ISSUE TITLE
OWFS Temperatur fehler "-1" ausblenden?

### ISSUE THREAD

**Issue by McDagobert** [ioBroker/ioBroker.owfs#5]
Hallo 
bei mir liefern die Temperatur Sensoren regelmäßig fehl Werte „-1“ kann man diese irgendwie ausblenden?

**Comment by passuff** [comment]
Warum gibt es diese falschen readouts überhaupt? Da ich mit den Werten Berechnungen durchführe, bekomme ich falsche Ergebnisse. Ich möchte ungern die Werte plausibilisieren.

So sieht bei mir das log aus:

`
2019-03-22 22:43:34.646 - debug: owfs.0 Read /28.FFE0D8601803/temperature
2019-03-22 22:43:34.647 - debug: owfs.0 Read /28.FFF08B601803/temperature
2019-03-22 22:43:34.647 - debug: owfs.0 Read /28.FFC2CC601803/temperature
2019-03-22 22:43:34.648 - debug: owfs.0 Read /28.FF7BC3601803/temperature
2019-03-22 22:43:34.648 - debug: owfs.0 Read /28.FFBFBE601803/temperature
2019-03-22 22:43:34.841 - debug: owfs.0 Read /28.FFF08B601803/temperature:37.3125
2019-03-22 22:43:35.972 - debug: owfs.0 Read /28.FFE0D8601803/temperature:25.25
2019-03-22 22:43:36.751 - debug: owfs.0 Read /28.FFBFBE601803/temperature:49.6875
2019-03-22 22:43:37.962 - debug: owfs.0 Read /28.FF7BC3601803/temperature:54.1875
2019-03-22 22:43:37.992 - warn: owfs.0 Cannot read value of /28.FFF08B601803/temperature: Error: -1
2019-03-22 22:43:38.801 - debug: owfs.0 Read /28.FFC2CC601803/temperature:35.4375
2019-03-22 22:43:39.649 - debug: owfs.0 Read /28.FFE0D8601803/temperature
2019-03-22 22:43:39.650 - debug: owfs.0 Read /28.FFF08B601803/temperature
2019-03-22 22:43:39.650 - debug: owfs.0 Read /28.FFC2CC601803/temperature
2019-03-22 22:43:39.651 - debug: owfs.0 Read /28.FF7BC3601803/temperature
2019-03-22 22:43:39.651 - debug: owfs.0 Read /28.FFBFBE601803/temperature
2019-03-22 22:43:40.471 - debug: owfs.0 Read /28.FFE0D8601803/temperature:25.25
2019-03-22 22:43:41.992 - debug: owfs.0 Read /28.FFC2CC601803/temperature:35.4375
2019-03-22 22:43:42.031 - debug: owfs.0 Read /28.FFBFBE601803/temperature:49.625
...
`
Wieso wird eigentlich jedes ID zwei Mal ausgelesene und warum kommt nur ein Mal ein Wert zurück?

**Comment by passuff** [comment]
seems like this development is dead...

**Comment by Apollon77** [comment]
Maybe solved in 0.6.0? Please verify

**Comment by Apollon77** [comment]
0.6.0 available on GitHub, please report back !

**Comment by passuff** [comment]
$ ./iobroker url "https://github.com/ioBroker/ioBroker.owfs"
install https://github.com/ioBroker/ioBroker.owfs/tarball/master
npm install https://github.com/ioBroker/ioBroker.owfs/tarball/master --production --save --prefix "/opt/iobroker" (System call)
../src/linux/DeviceINQ.cc:35:37: fatal error: bluetooth/bluetooth.h: Datei oder Verzeichnis nicht gefunden     #include <bluetooth/bluetooth.h>
                                     ^

compilation terminated.
make: *** [Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o] Fehler 1
gyp
 
ERR!
 
build error
 gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! 
stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)gyp ERR! stack     at emitTwo (events.js:126:13)
gyp
 ERR! stack     at ChildProcess.emit (events.js:214:7)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /opt/iobroker/node_modules/iobroker.radar2/node_modules/node-bluetooth
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

npm
 
WARN
 
enoent
 ENOENT: no such file or directory, open '/opt/iobroker/node_modules/node-bluetooth/package.json'
npm
 WARN react-beautiful-dnd@9.0.2 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.npm 
WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.npm WARN
 react-redux@5.1.1 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.npm 
WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.3 (node_modules/osx-temperature-sensor):npm
 WARN notsup
 SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm
 WARN optional
 SKIPPING OPTIONAL DEPENDENCY: node-bluetooth@1.2.5 (node_modules/iobroker.radar2/node_modules/node-bluetooth):npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: node-bluetooth@1.2.5 install: `node-gyp configure build`npm WARN 
optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by passuff** [comment]
Instanz gelöscht und wieder hinzugefügt.  Leider immer noch keine Option auffindbar!

**Comment by passuff** [comment]
owfs.0 | 2019-07-09 16:04:38.634 | warn | Cannot read value of /28.FFBFBE601803/temperature: Error: -1
-- | -- | -- | --

**Comment by Apollon77** [comment]
> Instanz gelöscht und wieder hinzugefügt. Leider immer noch keine Option auffindbar!

Auch nochmals neu von GitHub installiert?
ggf ein "iobroker upload owfs" bzw den Upload Btton drücken?

**Comment by Apollon77** [comment]
PS: naja mit dem Fehler oben hat er nichts aktualisiert!

--> https://stackoverflow.com/questions/23436909/where-is-the-bluetooth-bluetooth-h-located-in-linux ?!

**Comment by passuff** [comment]
> Auch nochmals neu von GitHub installiert?
ggf ein "iobroker upload owfs" bzw den Upload Btton drücken?

Alles versucht. Bringt keine Besserung.

> --> https://stackoverflow.com/questions/23436909/where-is-the-bluetooth-bluetooth-h-located-in-linux ?!

Was hat owfs mit bluetooth zu tun?

**Comment by passuff** [comment]
Hab das bluetooth lib installiert und den alten adapter gelöscht und anschließend neu von git geladen:

$ ./iobroker url "https://github.com/ioBroker/ioBroker.owfs"
install https://github.com/ioBroker/ioBroker.owfs/tarball/master
npm install https://github.com/ioBroker/ioBroker.owfs/tarball/master --production --save --prefix "/opt/iobroker" (System call)
npm
 
WARN
 
enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/node-bluetooth/package.json'npm
 WARN
 react-beautiful-dnd@9.0.2 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.npm WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm
 WARN react-redux@5.1.1 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.npm
 WARN 
optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.3 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


process exited with code 0

**Comment by Apollon77** [comment]
Warum auch immer ist kein upload erfolgt. 
Bitte iobroker upload owfs ausführen. Und Instanz neu starten. 

Dann?

Welche js-Controller Version?

**Comment by passuff** [comment]
Upload und Restart durchgeführt. Wofür ist ein Upload? Das habe ich bisher noch nie gebraucht und und ich finde auch keine Erklärung dazu...

js-controller: 1.5.12

Die Einstellungen der OWFS Instanz haben sich nicht verändert. Es gibt immer noch keine "Option" die Errors/-1 zu filtern.
Auch die Fehler sind nicht verschwunden:
`

owfs.0 | 2019-07-10 08:45:23.578 | warn | Cannot read value of /28.FF7BC3601803/temperature: Error: -1
-- | -- | -- | --


`

**Comment by Apollon77** [comment]
Also ... in den Settings ist neben dem Poll interval an sich ein setting "No state change on error". Dieses macht aktuell nicht die Meldung weg aber das die -1 in das State geschrieben wird.
Ich habe jetzt auf GitHub noch das Loglevel der Meldungen von warn auf info geändert ... 

Also bitte nochmal von Github installieren und prüfen. Ich wprde die Meldungen auf info belassen wollen, du kannst also daher wenn Sie dich nicht interessieren das Loglevel der Instanz ändern (Instanzen -> Expertenmodus -> Spalte Logstufe bei der Instanz)

**Comment by passuff** [comment]
Neu von git geladen, upload, Instanz neu gestartet und das Optionsfeld ist nun da :)
Loglevel und Wert werde ich berichten, sobald ich wieder einen Error bekomme..
