### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.owfs#6]
The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

**Comment by INgoRah** [comment]
Tryied to support the compact mode in the attached patch, but it seems to be not starting in the compact mode. Any feedback?

[Support-of-compact-mode-adapter.patch.txt](https://github.com/ioBroker/ioBroker.owfs/files/3365423/Support-of-compact-mode-adapter.patch.txt)

**Comment by Apollon77** [comment]
Do you have that in a fork or such available as full code?

**Comment by Apollon77** [comment]
And you have enabled compact mode correctly and used a js-controller n2.0 from GitHub?

**Comment by INgoRah** [comment]
Thanx for the feedback. Patch is attached. Yes, I used js-controller which supports it, other adpaters such a Telegram and javascript are running already in that mode.

**Comment by Apollon77** [comment]
Did you do a „iobroker upload adaptername“ after changing the io-package? Else check in object System.adapter.name.0 if the common.compact is set correctly

**Comment by INgoRah** [comment]
Ah, ok, upload did the job! Alexa2 is also done now. Will upload the patch there

**Comment by Apollon77** [comment]
cool thx!

**Comment by Apollon77** [comment]
thank you, will come in 0.6.0 soon

**Comment by Apollon77** [comment]
I also updated https://docs.google.com/spreadsheets/d/1OaimQZV-CbMHYNfBWwICe6qXgGxq2Mr2ec-kNMsUyvg/edit#gid=0

**Comment by INgoRah** [comment]
Did you forgot to import the patch? You've just changed the documentation for 0.6.0.

**Comment by Apollon77** [comment]
yes :-( fixed now :)

**Comment by Apollon77** [comment]
PS: my IDE somehow did not commited these changes .. strange ... needed to manually commit them
